---
title: "Cell cycle regression of Perturb-Seq data"
author: "David Wu"
output: html_notebook
---
## Purpose
Perform cell cycle regression of Perturb-Seq integrated data

## Setup 
Set working directory to project directory
```{r setup}
require(knitr)
opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

### Optionally convert this Rmd to R script 
```{r eval=FALSE}
current_file <- rstudioapi::getActiveDocumentContext()$path
output_file <- stringr::str_replace(current_file, '.Rmd', '.R')
knitr::purl(current_file, output = output_file)
file.edit(output_file)
```

### Load custom themes and functions
```{r, message=FALSE}
source('analysis/universal/themes.R') # themes for all project components

source('analysis/universal/functions.R') # themes for all project components
theme_set(theme_publication())

source('analysis/perturbseq/scripts/functions.R')  # functions for this component; may be empty
```

### Directories
```{r, message=FALSE}
analysis_dir <- 'analysis/perturbseq/output/009_cell_cycle_regression' # analysis file output directory
data_dir <- 'data/perturbseq/derived/seurat' # data file output directory

dir.create(analysis_dir, showWarnings = FALSE)
dir.create(data_dir, showWarnings = FALSE)
```

### Load libraries
```{r, message=FALSE}
library(tidyverse)
library(Seurat)
library(future)
options(future.globals.maxSize = 10 * 1024^3)
plan("multiprocess", workers = 24)
```

## Import integrated object

```{r}
tic()
merged <- read_rds('data/perturbseq/derived/seurat/unified_cellranger_sct.rds')
toc()
merged
```

## Cell cycle regression 
```{r message=FALSE}
tic()
cellcycle <- merged %>% ScaleData(vars.to.regress = c("S.Score", "G2M.Score"), features = rownames(merged))
toc()

Sys.time()
```



## Export
```{r message=FALSE}
cellcycle %>% write_rds(file.path(data_dir, 'unified_cellranger_sct_regressed.rds'))
```



## Session info
```{r}
sessionInfo()
```

