---
title: "Quality filtering of Perturb-Seq data"
author: "David Wu"
output: html_notebook
---
## Purpose
Perform QC of cells post-clustering and marker analysis 

Set working directory to project directory
```{r setup}
require(knitr)
opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

### Optionally convert this Rmd to R script 
```{r eval=FALSE, message=FALSE}
current_file <- rstudioapi::getActiveDocumentContext()$path
output_file <- stringr::str_replace(current_file, '.Rmd', '.R')
knitr::purl(current_file, output = output_file)
file.edit(output_file)
```

### Load custom themes and functions
```{r, message=FALSE}
source('analysis/universal/themes.R') # themes for all project components

source('analysis/universal/functions.R') # themes for all project components
theme_set(theme_publication())

source('analysis/perturbseq/scripts/functions.R')  # functions for this component; may be empty
```

### Directories
```{r, message=FALSE}
analysis_dir <- 'analysis/perturbseq/output/post_cluster_qc' # analysis file output directory
data_dir <- 'data/perturbseq/derived/seurat' # data file output directory

dir.create(analysis_dir, showWarnings = FALSE)
dir.create(data_dir, showWarnings = FALSE)
```

### Load libraries
```{r, message=FALSE}
library(tidyverse)
library(Seurat)
```

```{r}
reduced <- read_rds(file.path(data_dir, 'unified_cellranger_sct_reduced.rds'))
```
### Filter out QC clusters
```{r}
seurat_features(reduced, c('percent_mito', 'percent_ribo'))
```
```{r}
seurat_plot(reduced, feature = 'low_res_cluster')
```

```{r}
filtered_table <- reduced@meta.data %>% 
  rownames_to_column() %>% 
  filter(!(low_res_cluster %in% c(8, 14))) 
filtered <- subset(reduced, cells = filtered_table %>% pull(rowname))
filtered
```

```{r}
seurat_plot(filtered)
```

## Export
```{r}
filtered %>% write_rds(file.path(data_dir, 'unified_qc.rds'))
```


## Session info
```{r}
sessionInfo()
```

